### PR TITLE
Include errortext to provide transparent information about backend errors

### PR DESCRIPTION
**Pull request by 1605200517**
Addresses #110

### CODE REVIEW

**Comment by greut** [comment]
It looks nice. Although, I'd put that logic where the exception is shown to the user.

**Comment by 1605200517** [comment]
thank you @greut  - how do you mean, "put that logic where the exception is shown to the user"?
Do you mean around the line 288?

```
 if self.trace:
                print(response.status_code, response.reason, file=sys.stderr)
```

**Comment by greut** [comment]
@1605200517 cs is both a library and a client. If you're using the library, you'll have to do it yourself, when using the client (cli), that piece of code should have you covered.

https://github.com/exoscale/cs/blob/master/cs/__init__.py#L106-L121

**Comment by greut** [comment]
@1605200517 the trace option is more a _"full debug"_ mode flag than an error handling solution.

**Comment by greut** [comment]
The exception "message" is most of the tip the tip of the iceberg. E.g. when using the `requests` library, you'll have to dig the request and response argument as needed.

The `.response` is not part of `Exception`, hence you're breaking inheritance by assuming so.

When using `cs` as a library, hence not a a command line interface program, you're free to handle the exception they it pleases you.

**Comment by 1605200517** [comment]
I still miss the point why one would expect a user of the library to dig into the iceberg just to get a useful error message.

**Pull request closed without merging**
