### PR TITLE
csx: is the future

### PR DESCRIPTION
**Pull request by greut**
screenshot from 2018-03-23 08-34-26

screenshot from 2018-03-23 08-35-34

### CODE REVIEW

**Comment by pyr** [comment]
April 1st is 9 days from now.

**Comment by brutasse** [comment]
😱😱😱😱

**Comment by marcaurele** [comment]
😍😍😍😍🤣

**Comment by greut** [comment]
screenshot from 2018-03-23 15-09-51

screenshot from 2018-03-23 15-11-18

**Pull request closed without merging**
