### PR TITLE
fix python 2.6 compatibility

### PR DESCRIPTION
**Pull request by resmo**
I have to use python 2.6 on one host. Would be glad if you can merge it in.

### CODE REVIEW

**Comment by brutasse** [comment]
Sure, it's worth it :) Could you add a `py26` target to `tox.ini` and `.travis.yml` while you're at it? It'd help not breaking it in the future. Thanks!

**Comment by resmo** [comment]
yep, coming :)

**Comment by brutasse** [comment]
:shipit:

**Comment by brutasse** [comment]
Thanks!

**Comment by brutasse** [comment]
`0.6.1` is available on PyPI.

**Comment by resmo** [comment]
:+1:

**Pull request merged**
